dist: bionic

language: go

go:
  - 1.14.1

script:
  # - env GO111MODULE=on GOPRIVATE='github.com/mikelsr/*' go build -x
  - env GO111MODULE=on GOPRIVATE='github.com/mikelsr/*' go test -v --timeout 30s ./...
